### ISSUE TITLE
comprehensive-rust 的中文版本需要更新

### ISSUE THREAD

**Issue by hintcnuie** [jaywcjlove/rust-cn-document-for-docker#3]
comprehensive-rust 的中文版本需要更新， 请看本地docker 版本和网络版本的区别：

<img width="1345" alt="Screenshot 2024-02-19 at 00 35 02" src="https://github.com/jaywcjlove/rust-cn-document-for-docker/assets/4081542/dfa23be4-3fdb-4b0a-b9c6-7d051c8b2562">

**Comment by jaywcjlove** [comment]
@hintcnuie 已更新

新增

- Rust 算法题解
- Rust 语言风格指南
